modLoader = "javafml"
loaderVersion = "[45,)"
license = "ARR"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId = "ancientmagic"
version = "${file.jarVersion}"
displayName = "Ancient Magic"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="AncientMagic.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
# The description text for the mod (multi line!) (#mandatory)
description = '''

'''
[[dependencies.ancientmagic]]
modId = "forge"
mandatory = true
versionRange = "[45,)" #An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
[[dependencies.ancientmagic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ancientmagic]]
modId = "waystones"
mandatory = false
versionRange = ""
