package team.zeds.ancientmagic.api.except;

import java.io.Serial;

public class UnsupportedRegistryException extends RuntimeException {
    /**
     * Generated by JBR serialver.exe.
     * <br>
     * Learn more about JBR <a href="https://github.com/JetBrains/JetBrainsRuntime">here</a>
     * <br>
     * Learn more about serialver <a href="https://docs.oracle.com/en/java/javase/17/docs/specs/man/serialver.html">here</a>
     */
    @Serial
    private static final long serialVersionUID = -8997717281147608765L;

    public UnsupportedRegistryException(String message) {
        super(message);
    }

    public UnsupportedRegistryException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedRegistryException(Throwable cause) {
        super(cause);
    }

    protected UnsupportedRegistryException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
}
