/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package Effekseer.swig

class EffekseerTextureType {
    fun swigValue(): Int {
        return swigValue
    }

    override fun toString(): String {
        return swigName
    }

    private constructor(swigName: String) {
        this.swigName = swigName
        this.swigValue = swigNext++
    }

    private constructor(swigName: String, swigValue: Int) {
        this.swigName = swigName
        this.swigValue = swigValue
        swigNext = swigValue + 1
    }

    private constructor(swigName: String, swigEnum: EffekseerTextureType) {
        this.swigName = swigName
        this.swigValue = swigEnum.swigValue
        swigNext = this.swigValue + 1
    }

    private val swigValue: Int
    private val swigName: String

    companion object {
        val Color: EffekseerTextureType = EffekseerTextureType("Color")
        val Normal: EffekseerTextureType = EffekseerTextureType("Normal")
        val Distortion: EffekseerTextureType = EffekseerTextureType("Distortion")

        fun swigToEnum(swigValue: Int): EffekseerTextureType {
            if (swigValue < swigValues.size && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue) return swigValues[swigValue]
            for (i in swigValues.indices) if (swigValues[i].swigValue == swigValue) return swigValues[i]
            throw IllegalArgumentException("No enum " + EffekseerTextureType::class.java + " with value " + swigValue)
        }

        private val swigValues = arrayOf(Color, Normal, Distortion)
        private var swigNext = 0
    }
}

