/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package Effekseer.swig

class EffekseerCoreDeviceType {
    fun swigValue(): Int {
        return swigValue
    }

    override fun toString(): String {
        return swigName
    }

    private constructor(swigName: String) {
        this.swigName = swigName
        this.swigValue = swigNext++
    }

    private constructor(swigName: String, swigValue: Int) {
        this.swigName = swigName
        this.swigValue = swigValue
        swigNext = swigValue + 1
    }

    private constructor(swigName: String, swigEnum: EffekseerCoreDeviceType) {
        this.swigName = swigName
        this.swigValue = swigEnum.swigValue
        swigNext = this.swigValue + 1
    }

    private val swigValue: Int
    private val swigName: String

    companion object {
        val Unknown: EffekseerCoreDeviceType = EffekseerCoreDeviceType("Unknown")
        val OpenGL: EffekseerCoreDeviceType = EffekseerCoreDeviceType("OpenGL")
        val DirectX9: EffekseerCoreDeviceType = EffekseerCoreDeviceType("DirectX9")
        val DirectX11: EffekseerCoreDeviceType = EffekseerCoreDeviceType("DirectX11")

        fun swigToEnum(swigValue: Int): EffekseerCoreDeviceType {
            if (swigValue < swigValues.size && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue) return swigValues[swigValue]
            for (i in swigValues.indices) if (swigValues[i].swigValue == swigValue) return swigValues[i]
            throw IllegalArgumentException("No enum " + EffekseerCoreDeviceType::class.java + " with value " + swigValue)
        }

        private val swigValues = arrayOf(Unknown, OpenGL, DirectX9, DirectX11)
        private var swigNext = 0
    }
}

