modLoader="${modloader}"
loaderVersion="${mlVersion}"
license="${license}"
[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
credits="${credits}"
authors="${modAuthor}"
description='''
${description}
'''
[[mixins]]
    config="${modId}.mixins.json"
[[mixins]]
[[dependencies.${modId}]]
    modId="neoforge"
    type="required" # types: required, incompactable, optional or discouraged
    versionRange="${neoVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="minecraft"
    type="required"
    versionRange="${mcRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="kotlinforforge"
    type="required"
    reason="Mod requires KFF, i.e. it writted on Kotlin, not Java"
    versionRange="${kffRange}"
    ordering="NONE"
    side="BOTH"
