modLoader="kotlinforforge"
loaderVersion="[4.6,)"
license="All rights reserved"
[[mods]]
modId="aeternus"
version="${file.jarVersion}"
displayName="Aeternus"
credits="Thanks for this example mod goes to Java"
authors="AlgorithmLX, HollowHorizon, DizaGo Fox, sigma_veb, Goovy, _BENDY659_, _GuRmAn_"
description='''
Etherium-based magic mod
'''
[[dependencies.aeternus]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aeternus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aeternus]]
    modId="kotlinforforge"
